site_name: Bitchaser
site_description: Bitcoin forecasting using statistics and time-series analysis
site_author: Camden White
repo_url: https://github.com/camden-white/Bitchaser

theme:
  name: material

nav:
  - Home: index.md
